Add connected component image filter
BlueQuartzSoftware/ITKImageProcessing pull request #124
Opened 2017-01-27 23:00 UTC by fbudin69500

2017-01-27 23:33 UTC, thewtex requested changes
Great!

Suggested subGroup inline.

2017-01-27 23:33 UTC, thewtex commented on ITKImageProcessingFilters/ITKConnectedComponentImage.cpp
> +{ return "ITK ConnectedComponents"; }
ITK SegmentationPostProcessing

2017-01-27 23:58 UTC, fbudin69500 commented on ITKImageProcessingFilters/ITKConnectedComponentImage.cpp
> +{ return "ITK ConnectedComponents"; }
addressed.

2017-01-28 00:43 UTC, thewtex approved these changes

2017-01-29 02:23 UTC, merged