Fix crash due to import pointer being null
BlueQuartzSoftware/ITKImageProcessing pull request #169
Opened 2019-01-16 21:55 UTC by dzenanz

When output of InPlaceDream3DDataToImageFilter is cast to its base
itk::Image, the buffer is empty because the derived Dream3DImage has
a different buffer. The solution is to instantiate TileMontage
with Dream3DImage as the template image parameter.

2019-01-16 23:19 UTC, imikejackson commented
Looks good to me but we should have @tplatt77 and/or @joeykleingers take a look and try it.

2019-01-17 13:34 UTC, joeykleingers commented
I am still getting a crash on my machine, inside the itkTileMergeImageFilter's ResampleSingleRegion function, line 533.  It is trying to call begin() and end() on the 2524th element of m_RegionContributors, but m_RegionContributors is empty.  I included the crash report.. the crash is on thread 7.

[CrashReport.txt](https://github.com/BlueQuartzSoftware/ITKImageProcessing/files/2768834/CrashReport.txt)

2019-01-17 13:38 UTC, joeykleingers requested changes
I am still getting a crash on my machine when I compile and run this fix, inside the itkTileMergeImageFilter's ResampleSingleRegion function, line 533. It is trying to call begin() and end() on the 2524th element of m_RegionContributors, but m_RegionContributors is empty. I included the crash report.. the crash is on thread 7.

[CrashReport.txt](https://github.com/BlueQuartzSoftware/ITKImageProcessing/files/2768850/CrashReport.txt)

2019-01-17 15:25 UTC, joeykleingers commented
It turns out that I wasn't on the latest ITK commit.  It now completes without crashing.  However, the results I am getting after stitching are incorrect, and look like this:

<img width="789" alt="screen shot 2019-01-17 at 10 24 17 am" src="https://user-images.githubusercontent.com/6197698/51328746-0f65bc00-1a42-11e9-9008-0a01bcbcfe35.png">

I will look into why this is happening, but for now this pull request is complete and seems to fix the stitching crash.

2019-01-17 15:25 UTC, joeykleingers approved these changes

2019-01-17 15:26 UTC, merged